export const ROUTE_PATHS = {
    root: '/',
    landing: '/landing',
    login: '/login',
    oauthCallback: '/auth/callback',
    register: '/register',
    forget: '/forget-password',
    privacy: '/privacy',

    // serene
    home: '/serene',
    chat: '/serene/chat',
    reflect: '/serene/reflect',
    resources: '/serene/resources',
    nutrition: '/serene/nutrition',
    support: '/serene/support',
    profile: '/serene/profile',
    setting: '/serene/setting',
    notifications: '/serene/notifications',

    // onboarding & flows
    onboardingPolicy: '/onboarding/policy',
    onboarding: '/serene/onboarding',
    bamboo: '/serene/bamboo',
    safetyCheck: '/serene/safety-check',
    checkin: '/serene/checkin',
    screening: '/serene/screening',
    results: '/serene/results',
    exercises: '/serene/exercises',
    anxietyBreathingExercise: '/serene/exercises?exercise=anxiety_breathing',
    rewards: '/serene/rewards',

    //admin
    admin: '/admin',
    adminLogin: '/admin/login',
    adminDashboard: '/admin/dashboard',
    adminCrisisLogs: '/admin/crisis-logs',
    adminResources: '/admin/resources',
    adminUsers: '/admin/users',
    adminLetters: '/admin/letters',
    adminAuditLogs: '/admin/audit-logs',
    adminNotifications: '/admin/notifications',
    adminAnalytics: '/admin/analytics',
    adminAutomation: '/admin/automation',
} as const
