"""Move sync_outbox identity repair out of FastAPI startup.

Revision ID: 0018_sync_outbox_identity_contract
Revises: 0017_admin_audit_log_schema_alignment
Create Date: 2026-05-08
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "0018_outbox_identity"
down_revision = "0017_admin_audit_align"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return

    op.execute(
        sa.text(
            """
            DO $$
            DECLARE
              identity_generation text;
              column_default text;
            BEGIN
              IF to_regclass('app.sync_outbox') IS NULL THEN
                RETURN;
              END IF;

              SELECT c.identity_generation, c.column_default
                INTO identity_generation, column_default
              FROM information_schema.columns c
              WHERE c.table_schema = 'app'
                AND c.table_name = 'sync_outbox'
                AND c.column_name = 'outbox_id';

              IF identity_generation IS NULL AND column_default IS NULL THEN
                ALTER TABLE app.sync_outbox
                  ALTER COLUMN outbox_id
                  ADD GENERATED BY DEFAULT AS IDENTITY;
              END IF;
            END $$;
            """
        )
    )


def downgrade() -> None:
    return
