from contextlib import asynccontextmanager
import threading
import time

from fastapi import FastAPI, Request
from fastapi.exceptions import RequestValidationError
from fastapi.responses import JSONResponse
from sqlalchemy import text

from app.api.v1.api import api_router
from app.core.config import get_settings
from app.core.errors import AppError
from app.core.responses import fail
from app.db.init_db import init_db
from app.db.session import get_session_factory
from fastapi.middleware.cors import CORSMiddleware

settings = get_settings()


def _backfill_policy_versions() -> None:
    try:
        factory = get_session_factory()
        db = factory()
        try:
            db.execute(
                text(
                    "ALTER TABLE sync_outbox  "
                    "ALTER COLUMN outbox_id  "
                    "ADD GENERATED BY DEFAULT AS IDENTITY"
                )
            )
            db.commit()
        finally:
            db.close()
    except Exception:
        pass


def _idle_loop() -> None:
    from app.services.idle_sessions import summarize_idle_sessions

    while True:
        time.sleep(120)
        try:
            summarize_idle_sessions()
        except Exception:
            pass


@asynccontextmanager
async def lifespan(_: FastAPI):
    if settings.auto_create_schema:
        init_db()
    _backfill_policy_versions()
    threading.Thread(target=_idle_loop, daemon=True).start()
    yield


app = FastAPI(
    title=settings.app_name,
    version=settings.app_version,
    lifespan=lifespan,
)
origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:4173",
    "http://127.0.0.1:4173",
    "http://127.0.0.1:5500",
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],   # GET, POST, PUT...
    allow_headers=["*"],   # Authorization, Content-Type...
)
app.include_router(api_router, prefix=settings.api_prefix)


@app.exception_handler(AppError)
def app_error_handler(_: Request, exc: AppError):
    return fail(exc.code, exc.message, exc.status_code)


@app.exception_handler(RequestValidationError)
def validation_error_handler(_: Request, exc: RequestValidationError):
    return fail("INVALID_PARAMETER", str(exc.errors()), 400)


@app.exception_handler(Exception)
def fallback_handler(_: Request, __: Exception):
    return fail("SCHEMA_VALIDATION_FAILED", "Đã xảy ra lỗi nội bộ", 500)


@app.get("/health")
def health():
    return JSONResponse(content={"status": "ok"})
